In [18]:
import numpy as np
import pandas as pd

Loading Dataset

In [19]:
df = pd.read_csv('countries.csv')
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

Basic Information about Dataset

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

Dataset Shape (Rows & Columns)

In [21]:
df.shape

(194, 64)

Column Names

In [22]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

Sort Countries by Population (Top 5)

In [23]:
df.sort_values('population', ascending=False, inplace=True)
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.0,-97.0,4058100.0,...,333287557,28.7037,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.0,120.0,623000.0,...,275501339,21.9130,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
129,Pakistan,Islamic Republic of Pakistan,Pakistani rupee,Islamabad,Southern Asia,Asia,Pakistani,30.0,70.0,367230.0,...,235824862,20.4678,146845783,88979079,1.71,4.17,Hybrid regime,16.5,Imran Khan,Prime Minister

Total Population of all Countries Combined

In [24]:
total_population = df['population'].sum()
print(f'Total population: {total_population}')

Total population: 7913042291

Select Specific Columns

In [25]:
df[['country', 'population']].head(10)

           country  population
75           India  1417173173
34           China  1412175000
184  United States   333287557
76       Indonesia   275501339
129       Pakistan   235824862
125        Nigeria   218541212
22          Brazil   215313498
12      Bangladesh   171186372
140         Russia   143555736
109         Mexico   127504125

List all Unique Components in Dataset

In [26]:
continents = df['continent'].unique()
print(f'Continents: {continents}')

Continents: ['Asia' 'Americas' 'Africa' 'Europe' 'Oceania']

Country with Highest GDP

In [27]:
highest_gdp_country = df.loc[df['gdp'].idxmax(), 'country']
print(f'Country with highest GDP: {highest_gdp_country}')

Country with highest GDP: United States

Countries present in Asia

In [28]:
asia_countries = df[df['continent'] == 'Asia']
asia_countries.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.0,120.0,623000.0,...,275501339,21.9130,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
129,Pakistan,Islamic Republic of Pakistan,Pakistani rupee,Islamabad,Southern Asia,Asia,Pakistani,30.0,70.0,367230.0,...,235824862,20.4678,146845783,88979079,1.71,4.17,Hybrid regime,16.5,Imran Khan,Prime Minister
12,Bangladesh,People's Republic of Bangladesh,Bangladeshi taka,Dhaka,Southern Asia,Asia,Bangladeshi,24.0,90.0,99010.0,...,171186372,20.8571,103206552,67979820,1.54,5.57,Hybrid regime,22.7,Sheikh Hasina,Prime Minister

Create a New Column called gdp_per_capita

In [30]:
df['gdp_per_capita'] = df['gdp'] / df['population']
df[['country', 'gdp_per_capita']].head()

           country  gdp_per_capita
75           India     2388.621281
34           China    12720.236515
184  United States    76398.591742
76       Indonesia     4787.998508
129       Pakistan     1596.663714

Country with Highest GDP per Capita

In [31]:
richest_per_capita = df.loc[df['gdp_per_capita'].idxmax(), 'country']
print(f'Country with highest GDP per capita: {richest_per_capita}')

Country with highest GDP per capita: Monaco

Country with Smallest Land Area

In [33]:
smallest_country = df.loc[df['land_area'].idxmin(), 'country']
print(f'Smallest country by area: {smallest_country}')

Smallest country by area: Monaco

Top 5 Countries with Highest Inflation Rates

In [36]:
high_inflation = df.sort_values('inflation', ascending=False).head(5)
high_inflation[['country', 'inflation']]

       country  inflation
188  Venezuela   254.9490
93     Lebanon   154.7560
162      Sudan   138.8080
193   Zimbabwe   104.7050
177     Turkey    72.3088

Slice the Dataframe to show only the country, capital_city, and currency for the First 10 Rows.

In [42]:
subset = df.loc[:9, ['country', 'population', 'gdp']]
print(subset)

                  country  population           gdp
75                  India  1417173173  3.385090e+12
34                  China  1412175000  1.796320e+13
184         United States   333287557  2.546270e+13
76              Indonesia   275501339  1.319100e+12
129              Pakistan   235824862  3.765330e+11
..                    ...         ...           ...
73                Hungary     9683505  1.787890e+11
80                 Israel     9550600  5.220330e+11
182  United Arab Emirates     9441129  5.075350e+11
14                Belarus     9208701  7.279350e+10
9                 Austria     9042528  4.714000e+11

[98 rows x 3 columns]

Average Population by Region

In [43]:
df.groupby('region')['population'].mean()

region
Australia and New Zealand    1.555152e+07
Caribbean                    3.053804e+06
Central America              2.232179e+07
Central Asia                 1.569139e+07
Eastern Africa               2.710280e+07
Eastern Asia                 3.236792e+08
Eastern Europe               2.819816e+07
Melanesia                    3.030850e+06
Micronesia                   6.353760e+04
Middle Africa                2.069911e+07
Northern Africa              4.323233e+07
Northern America             1.861087e+08
Northern Europe              1.059054e+07
Polynesia                    1.135173e+05
South America                3.643607e+07
South-Eastern Asia           6.188967e+07
Southern Africa              1.371974e+07
Southern Asia                2.230998e+08
Southern Europe              1.004744e+07
Western Africa               2.681747e+07
Western Asia                 1.720938e+07
Western Europe               2.221409e+07
Name: population, dtype: float64

Country Count per Region

In [46]:
df.groupby('region')['country'].count()

region
Australia and New Zealand     2
Caribbean                    13
Central America               8
Central Asia                  5
Eastern Africa               17
Eastern Asia                  5
Eastern Europe               10
Melanesia                     4
Micronesia                    5
Middle Africa                10
Northern Africa               6
Northern America              2
Northern Europe              10
Polynesia                     3
South America                12
South-Eastern Asia           11
Southern Africa               5
Southern Asia                 9
Southern Europe              15
Western Africa               16
Western Asia                 17
Western Europe                9
Name: country, dtype: int64

Find a Specific Country

In [47]:
df[df['country'] == 'Pakistan']

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,gdp_per_capita
129,Pakistan,Islamic Republic of Pakistan,Pakistani rupee,Islamabad,Southern Asia,Asia,Pakistani,30.0,70.0,367230.0,...,20.4678,146845783,88979079,1.71,4.17,Hybrid regime,16.5,Imran Khan,Prime Minister,1596.663714